version: '3.8'

services:
  spark-data:
    driver_opts:
      type: none
      device: /home/indika_kuma/data
      o: bind
  spark-driver-app:
    image: jupyter/all-spark-notebook:spark-3.1.2
    container_name: spark-driver-app
    user: root
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/
      - spark-data:/opt/shareddatadir
  spark-master:
    build: ./spark-bitnami-python3.9
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_DAEMON_MEMORY=2G
      - SPARK_MASTER_OPTS="-Dspark.deploy.defaultCores=1"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-data:/opt/shareddatadir
  spark-worker-1:
    build: ./spark-bitnami-python3.9
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
     - "8081:8081"
    volumes:
      - spark-data:/opt/shareddatadir
  spark-worker-2:
    build: ./spark-bitnami-python3.9
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8082:8081"
    volumes:
      - spark-data:/opt/shareddatadir